env:
  INTEGROMAT_WEBHOOK_URL: ENCRYPTED[3f760bb35afbfa38ac940b7da7697b75cd220d74db6af093c0a34b6420663d14a71979a594b36250cf18e6cfd7ba72c6]

cirrus_container_task:
  only_if: &path-filter "changesInclude('.cirrus.yml', '.ci/*')"
  auto_cancellation: true
  container:
    image: gcc:latest
  matrix:
    - env:
        PARALLEL_NO: 1
    - env:
        PARALLEL_NO: 2
    - env:
        PARALLEL_NO: 3
    - env:
        PARALLEL_NO: 4
    - env:
        PARALLEL_NO: 5
    - env:
        PARALLEL_NO: 6
    - env:
        PARALLEL_NO: 7
    - env:
        PARALLEL_NO: 8
  env:
    TYPE: job
    SLEEP_SECONDS: 360
    JOB_NAME_PREFIX: ${CIRRUS_TASK_NAME}
  prallel_script: bash ./.ci/report.sh

cirrus_osx_task:
  only_if: *path-filter
  auto_cancellation: true
  osx_instance:
    image: catalina-xcode
  env:
    PARALLEL_NO: 9
    TYPE: job
    SLEEP_SECONDS: 360
    JOB_NAME_PREFIX: ${CIRRUS_TASK_NAME}
  prallel_script: ./.ci/report.sh

cirrus_freebsd_task:
  only_if: *path-filter
  auto_cancellation: true
  freebsd_instance:
    image_family: freebsd-12-1-snap
  matrix:
    - env:
        PARALLEL_NO: 10
    - env:
        PARALLEL_NO: 11
  env:
    TYPE: job
    SLEEP_SECONDS: 360
    JOB_NAME_PREFIX: ${CIRRUS_TASK_NAME}
  prallel_script: ./.ci/report.sh

cirrus_windows_task:
  only_if: *path-filter
  auto_cancellation: true
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  matrix:
    - env:
        PARALLEL_NO: 12
    - env:
        PARALLEL_NO: 13
  env:
    TYPE: job
    SLEEP_SECONDS: 360
    JOB_NAME_PREFIX: ${CIRRUS_TASK_NAME}
  prallel_script: .ci/report.bat
