kind: pipeline
type: docker
name: parallel1

environment:
  JOB_NAME_PREFIX: parallel1
  TYPE: step
  DRYRUN: "true"

steps:
- &base
  name: parallel1-1
  image: golang
  environment:
    PARALLEL_NO: 1
    INTEGROMAT_WEBHOOK_URL:
      from_secret: INTEGROMAT_WEBHOOK_URL
  commands:
    - "./.ci/report.sh"
  depends_on: [ clone ]
- <<: *base
  name: parallel1-2
  environment:
    PARALLEL_NO: 2

---

kind: pipeline
type: docker
name: parallel2

environment:
  JOB_NAME_PREFIX: parallel2
  TYPE: step
  DRYRUN: "true"

steps:
- &base
  name: parallel2-1
  image: golang
  environment:
    PARALLEL_NO: 3
    INTEGROMAT_WEBHOOK_URL:
      from_secret: INTEGROMAT_WEBHOOK_URL
  commands:
    - "./.ci/report.sh"
  depends_on: [ clone ]
- <<: *base
  name: parallel2-2
  environment:
    PARALLEL_NO: 4
- <<: *base
  name: parallel2-3
  environment:
    PARALLEL_NO: 5
- <<: *base
  name: parallel2-4
  environment:
    PARALLEL_NO: 6
- <<: *base
  name: parallel2-5
  environment:
    PARALLEL_NO: 7
- <<: *base
  name: parallel2-6
  environment:
    PARALLEL_NO: 8
- <<: *base
  name: parallel2-7
  environment:
    PARALLEL_NO: 9
- <<: *base
  name: parallel2-8
  environment:
    PARALLEL_NO: 10
- <<: *base
  name: parallel2-9
  environment:
    PARALLEL_NO: 11
- <<: *base
  name: parallel2-10
  environment:
    PARALLEL_NO: 12
- <<: *base
  name: parallel2-11
  environment:
    PARALLEL_NO: 13
- <<: *base
  name: parallel2-12
  environment:
    PARALLEL_NO: 14
- <<: *base
  name: parallel2-13
  environment:
    PARALLEL_NO: 15
- <<: *base
  name: parallel2-14
  environment:
    PARALLEL_NO: 16
- <<: *base
  name: parallel2-15
  environment:
    PARALLEL_NO: 17
- <<: *base
  name: parallel2-16
  environment:
    PARALLEL_NO: 18
- <<: *base
  name: parallel2-17
  environment:
    PARALLEL_NO: 19
- <<: *base
  name: parallel2-18
  environment:
    PARALLEL_NO: 20
- <<: *base
  name: parallel2-19
  environment:
    PARALLEL_NO: 21
- <<: *base
  name: parallel2-20
  environment:
    PARALLEL_NO: 22
- <<: *base
  name: parallel2-21
  environment:
    PARALLEL_NO: 23
- <<: *base
  name: parallel2-22
  environment:
    PARALLEL_NO: 24
- <<: *base
  name: parallel2-23
  environment:
    PARALLEL_NO: 25
- <<: *base
  name: parallel2-24
  environment:
    PARALLEL_NO: 26
- <<: *base
  name: parallel2-25
  environment:
    PARALLEL_NO: 27
- <<: *base
  name: parallel2-26
  environment:
    PARALLEL_NO: 28
- <<: *base
  name: parallel2-27
  environment:
    PARALLEL_NO: 29
- <<: *base
  name: parallel2-28
  environment:
    PARALLEL_NO: 30

---

kind: pipeline
type: docker
name: parallel3

environment:
  JOB_NAME_PREFIX: parallel3
  TYPE: step
  DRYRUN: "true"

steps:
- &base
  name: parallel3-1
  image: golang
  environment:
    PARALLEL_NO: 31
    INTEGROMAT_WEBHOOK_URL:
      from_secret: INTEGROMAT_WEBHOOK_URL
  commands:
    - "./.ci/report.sh"
  depends_on: [ clone ]
- <<: *base
  name: parallel3-2
  environment:
    PARALLEL_NO: 32
- <<: *base
  name: parallel3-3
  environment:
    PARALLEL_NO: 33
- <<: *base
  name: parallel3-4
  environment:
    PARALLEL_NO: 34
- <<: *base
  name: parallel3-5
  environment:
    PARALLEL_NO: 35
- <<: *base
  name: parallel3-6
  environment:
    PARALLEL_NO: 36
- <<: *base
  name: parallel3-7
  environment:
    PARALLEL_NO: 37
- <<: *base
  name: parallel3-8
  environment:
    PARALLEL_NO: 38
- <<: *base
  name: parallel3-9
  environment:
    PARALLEL_NO: 39
- <<: *base
  name: parallel3-10
  environment:
    PARALLEL_NO: 40

---

kind: pipeline
type: docker
name: parallel4

environment:
  JOB_NAME_PREFIX: parallel4
  TYPE: step
  DRYRUN: "true"

steps:
- &base
  name: parallel4-1
  image: golang
  environment:
    PARALLEL_NO: 41
    INTEGROMAT_WEBHOOK_URL:
      from_secret: INTEGROMAT_WEBHOOK_URL
  commands:
    - "./.ci/report.sh"
  depends_on: [ clone ]
- <<: *base
  name: parallel4-2
  environment:
    PARALLEL_NO: 42
- <<: *base
  name: parallel4-3
  environment:
    PARALLEL_NO: 43
- <<: *base
  name: parallel4-4
  environment:
    PARALLEL_NO: 44
- <<: *base
  name: parallel4-5
  environment:
    PARALLEL_NO: 45
- <<: *base
  name: parallel4-6
  environment:
    PARALLEL_NO: 46
- <<: *base
  name: parallel4-7
  environment:
    PARALLEL_NO: 47
- <<: *base
  name: parallel4-8
  environment:
    PARALLEL_NO: 48
- <<: *base
  name: parallel4-9
  environment:
    PARALLEL_NO: 49
- <<: *base
  name: parallel4-10
  environment:
    PARALLEL_NO: 50
