kind: pipeline
type: docker
name: parallel container

environment:
  JOB_NAME_PREFIX: parallel1-1
  TYPE: step
  INTEGROMAT_WEBHOOK_URL:
    from_secret: INTEGROMAT_WEBHOOK_URL

steps:
- name: &base parallel1-1
  image: golang
  environment:
    PARALLEL_NO: 1
  commands:
    - "./.ci/report.sh"
- <<: *base
  name: parallel1-2
  environment:
    PARALLEL_NO: 2
  depends_on:
    - parallel1-1
- <<: *base
  name: parallel1-3
  environment:
    PARALLEL_NO: 3
  depends_on:
    - parallel1-1

---

kind: pipeline
type: docker
name: parallel container

environment:
  JOB_NAME_PREFIX: parallel1-2
  TYPE: step
  INTEGROMAT_WEBHOOK_URL:
    from_secret: INTEGROMAT_WEBHOOK_URL

steps:
- name: &base parallel2
  image: golang
  environment:
    PARALLEL_NO: 4
  commands:
    - "./.ci/report.sh"
