kind: pipeline
type: docker
name: spec container

matrix:
  PARALLEL_NO:
    - 1
    - 2

steps:
- name: spec
  image: golang
  environment:
    TYPE: job
    INTEGROMAT_WEBHOOK_URL:
      from_secret: INTEGROMAT_WEBHOOK_URL
  commands:
    - "./.ci/report.sh"
