kind: pipeline
type: docker
name: parallel1

environment:
  JOB_NAME_PREFIX: parallel1
  TYPE: step

steps:
- &base
  name: parallel1-1
  image: golang
  environment:
    PARALLEL_NO: 1
    INTEGROMAT_WEBHOOK_URL:
      from_secret: INTEGROMAT_WEBHOOK_URL
  commands:
    - "./.ci/report.sh"
  depends_on: []
- <<: *base
  name: parallel1-2
  environment:
    PARALLEL_NO: 2

---

kind: pipeline
type: docker
name: parallel2

environment:
  JOB_NAME_PREFIX: parallel2
  TYPE: step

steps:
- &base
  name: parallel2
  image: golang
  environment:
    PARALLEL_NO: 3
    INTEGROMAT_WEBHOOK_URL:
      from_secret: INTEGROMAT_WEBHOOK_URL
  commands:
    - "./.ci/report.sh"
