checks:
  python:
    code_rating: true
    duplicate_code: true
build:
    environment:
      variables:
        TYPE: 'step'
    nodes:
      analysis:
        project_setup:
          override:
            - 'true'
        tests:
          override:
            - py-scrutinizer-run
            -
              command: pylint-run
              use_website_config: true
            -
              command: ./.ci/report.sh 1
              on_node: 1
              idle_timeout: 600
            -
              command: ./.ci/report.sh 2
              on_node: 2
              idle_timeout: 600
filter:
  excluded_paths:
    - '*/test/*'
  dependency_paths:
    - 'lib/*'
