trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - azure-pipelines.yml
      - .ci/*

strategy:
  matrix:
    Build1:
      PARALLEL_NO: 1
    Build2:
      PARALLEL_NO: 2
    Build3:
      PARALLEL_NO: 3
    Build4:
      PARALLEL_NO: 4
    Build5:
      PARALLEL_NO: 5
    Build6:
      PARALLEL_NO: 6
    Build7:
      PARALLEL_NO: 7
    Build8:
      PARALLEL_NO: 8
    Build9:
      PARALLEL_NO: 9
    Build10:
      PARALLEL_NO: 10
    Build11:
      PARALLEL_NO: 11
    Build12:
      PARALLEL_NO: 12

pool:
  vmImage: ubuntu-latest

steps:
- bash: ./.ci/report.sh
  env:
    INTEGROMAT_WEBHOOK_URL: $(INTEGROMAT_WEBHOOK_URL)
    TYPE: step
    DRYRUN: "true"
  displayName: 'parallel'
