version: '1.0'
stages:
  - checkout
  - parallel

steps:
  main_clone:
    title: clone
    type: git-clone
    stage: checkout
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
  ParallelTests1:
    type: parallel
    stage: parallel
    steps:
      parallel1: &base
        title: Parallel
        image: gcc:9
        # environment:
        #   - TYPE=step
        #   - JOB_NAME=ParallelTests1 1
        #   - PARALLEL_NO=1
        commands:
          - export TYPE=step
          - export JOB_NAME=ParallelTests1 1
          - export PARALLEL_NO=1
          - ./.ci/report.sh
      parallel2:
        <<: *base
        title: Paralle2
        commands:
          - export TYPE=step
          - export JOB_NAME=ParallelTests1 2
          - export PARALLEL_NO=1
          - ./.ci/report.sh
  ParallelTests2:
    type: parallel
    stage: parallel
    steps:
      parallel3:
        <<: *base
        title: Paralle3
        commands:
          - export TYPE=step
          - export JOB_NAME=ParallelTests2 1
          - export PARALLEL_NO=1
          - ./.ci/report.sh
      parallel4:
        <<: *base
        title: Paralle4
        commands:
          - export TYPE=step
          - export JOB_NAME=ParallelTests2 2
          - export PARALLEL_NO=1
          - ./.ci/report.sh
