version: '1.0'
stages:
  - checkout
  - prepare
  - parallel

steps:
  main_clone:
    title: clone
    type: git-clone
    stage: checkout
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    when:
      condition: &skip-condition
        all:
          noSkipCiInCommitMessageCiSkip: |
            includes(lower("${{CF_COMMIT_MESSAGE}}"), "[ci skip]") == false
          noSkipCiInCommitMessageSkipCI: |
            includes(lower("${{CF_COMMIT_MESSAGE}}"), "[skip ci]") == false
  prepareEnvironmentVariable:
    title: Reading GitHub token / Set Environment variable
    image: codefresh/cli
    stage: prepare
    commands:
      - cf_export GITHUB_TOKEN=$(codefresh get context github --decrypt -o yaml | yq -y .spec.data.auth.password)
      - cf_export DRYRUN:true
  updateSubmodules:
    image: codefresh/cfstep-gitsubmodules
    stage: prepare
    environment:
      - CF_SUBMODULE_SYNC=true
      - CF_SUBMODULE_UPDATE_RECURSIVE=true
  ParallelTests1:
    type: parallel
    stage: parallel
    when: *skip-condition
    steps:
      parallel1: &base
        title: Parallel
        image: gcc:9
        environment:
          - TYPE=step
          - JOB_NAME_PREFIX=ParallelTests1
          - PARALLEL_NO=1
        commands:
          - ./.ci/report.sh
      parallel2:
        <<: *base
        title: Paralle2
        environment:
          - TYPE=step
          - JOB_NAME_PREFIX=ParallelTests1
          - PARALLEL_NO=2
  ParallelTests2:
    type: parallel
    stage: parallel
    when: *skip-condition
    steps:
      parallel3:
        <<: *base
        title: Paralle3
        environment:
          - TYPE=step
          - JOB_NAME_PREFIX=ParallelTests2
          - PARALLEL_NO=3
      parallel4:
        <<: *base
        title: Paralle4
        environment:
          - TYPE=step
          - JOB_NAME_PREFIX=ParallelTests2
          - PARALLEL_NO=4
