version: 2.1

commands:
  parallel:
    parameters:
      index:
        type: integer
    steps:
      - checkout
      - export PARALLEL_NO=$(($CIRCLE_NODE_INDEX + << parameters.index >>))
      - run: ./.ci/report.sh

base: &base
  parallelism: 4
  parameters:
    index:
      type: integer
  docker:
    - image: circleci/buildpack-deps:cosmic-browsers
  environment:
    TYPE: step
  steps:
    - parallel:
      index: << parameters.index >>

jobs:
  parallel1:
    <<: *base
  parallel2:
    <<: *base

workflows:
  version: 2
  default-test:
    jobs:
      - parallel1
        index: 0
      - parallel2
        index: 4
