version: 2.1

commands:
  parallel:
    parameters:
      i:
        type: integer
        default: 0
    steps:
      - checkout
      - run:
          command: |
            export INDEX=$(($CIRCLE_NODE_INDEX + 1))
            export REPORT_JOB_NAME="${CIRCLE_JOB} ${INDEX}/${CIRCLE_NODE_TOTAL}"
            export PARALLEL_NO=$(($CIRCLE_NODE_INDEX + << parameters.i >>))
            ./.ci/report.sh

base1: &base1
  parallelism: 1
  parameters:
    i:
      type: integer
      default: 0
  # machine: true
  docker:
    - image: circleci/buildpack-deps:cosmic-browsers
  environment:
    TYPE: step
    # DRYRUN: true
  steps:
    - parallel:
        i: << parameters.i >>

base2: &base2
  <<: *base1
  parallelism: 2

base4: &base4
  <<: *base1
  parallelism: 4

base16: &base16
  <<: *base1
  parallelism: 16

base30: &base30
  <<: *base1
  parallelism: 30

jobs:
  parallel30:
    <<: *base30
  parallel16:
    <<: *base16
  parallel4a:
    <<: *base4
  parallel4b:
    <<: *base4
  parallel4c:
    <<: *base4
  parallel2:
    <<: *base2
  parallel1:
    <<: *base1

workflows:
  default-test:
    jobs:
      #====================================
      # 4x8 + 2x2
      # = 30 -> 6
      # - parallel4a:
      #     matrix:
      #       parameters:
      #         i: [0, 4, 8, 12, 16, 20, 24, 28]
      # - parallel2:
      #     matrix:
      #       parameters:
      #         i: [32, 34]
      #====================================
      # 4x1 + 4x7 + 2x1
      # = 30 -> 4
      # - parallel4a:
      #     i: 0
      # - parallel4b:
      #     matrix:
      #       parameters:
      #         i: [4, 8, 12, 16, 20, 24, 28]
      # - parallel2:
      #     matrix:
      #       parameters:
      #         i: [32]
      #====================================
      # 4x7 + 2x1 + 4x1
      # = 30 -> 4
      # - parallel4a:
      #     matrix:
      #       parameters:
      #         i: [0, 4, 8, 12, 16, 20, 24]
      # - parallel2:
      #     matrix:
      #       parameters:
      #         i: [28]
      # - parallel4b:
      #     matrix:
      #       parameters:
      #         i: [30]
      #====================================
      # 4x8 + 2x1
      # = 30 -> 4
      # - parallel4a:
      #     matrix:
      #       parameters:
      #         i: [0, 4, 8, 12, 16, 20, 24, 28]
      # - parallel2:
      #     matrix:
      #       parameters:
      #         i: [32]
      #====================================
      # 4x7 + 2x1
      # = 30
      # - parallel4a:
      #     matrix:
      #       parameters:
      #         i: [0, 4, 8, 12, 16, 20, 24]
      # - parallel2:
      #     matrix:
      #       parameters:
      #         i: [28]
      #====================================
      # 4x8
      # = 28 -> 4
      # - parallel4a:
      #     matrix:
      #       parameters:
      #         i: [0, 4, 8, 12, 16, 20, 24, 28]
      #====================================
      # 2x16
      # = 30 -> 2
      # - parallel2:
      #     matrix:
      #       parameters:
      #         i: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]
      #====================================
      # 1x31
      # = 30 -> 1
      # - parallel1:
      #     matrix:
      #       parameters:
      #         i: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
      #====================================
      # 16x2
      # =
      - parallel16:
          matrix:
            parameters:
              i: [0, 16]
