version: 2.1

commands:
  parallel:
    parameters:
      i:
        type: integer
        default: 0
    steps:
      - checkout
      - run:
          command: |
            export REPORT_JOB_NAME="${CIRCLE_JOB} ${CIRCLE_NODE_INDEX}/${CIRCLE_NODE_TOTAL}"
            export PARALLEL_NO=$(($CIRCLE_NODE_INDEX + << parameters.i >>))
            ./.ci/report.sh

base1: &base1
  parallelism: 1
  parameters:
    i:
      type: integer
      default: 0
  docker:
    - image: circleci/buildpack-deps:cosmic-browsers
  environment:
    TYPE: step
    # DRYRUN: true
  steps:
    - parallel:
        i: << parameters.i >>

base2: &base1
  parallelism: 2

base4: &base4
  <<: *base1
  parallelism: 4

jobs:
  parallel1:
    <<: *base4
  parallel2:
    <<: *base4
  parallel3:
    <<: *base2
  parallel4:
    <<: *base4
  parallel5:
    <<: *base5

workflows:
  default-test:
    jobs:
      # - parallel1:
      #     i: 0
      # - parallel2:
      #     matrix:
      #       parameters:
      #         i: [4, 8, 12, 16, 20, 24]
      # - parallel3:
      #     matrix:
      #       parameters:
      #         i: [28, 30]
      # - parallel4:
      #     i: 32
      - parallel5:
          matrix:
            parameters:
              i: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
