version: 2.1

commands:
  parallel:
    parameters:
      i:
        type: integer
        default: 0
    steps:
      - checkout
      - run:
          command: |
            export JOB_NAME="${CIRCLE_JOB} ${CIRCLE_NODE_INDEX}/${CIRCLE_NODE_TOTAL}"
            export PARALLEL_NO=$(($CIRCLE_NODE_INDEX + << parameters.i >>))
            ./.ci/report.sh

base: &base
  parallelism: 4
  parameters:
    i:
      type: integer
      default: 0
  docker:
    - image: circleci/buildpack-deps:cosmic-browsers
  environment:
    TYPE: step
  steps:
    - parallel:
        i: << parameters.i >>

jobs:
  parallel1:
    <<: *base
  parallel2:
    <<: *base

workflows:
  default-test:
    jobs:
      - parallel1:
          i: 0
      - parallel2:
          i: 4
