version: 2.1

base: &base
  parallelism: 4
  docker:
    - image: circleci/buildpack-deps:cosmic-browsers
  environment:
    TYPE: step
    PARALLEL_NO: $CIRCLE_NODE_INDEX
  steps:
    - checkout
    - run: ./.ci/report.sh

jobs:
  parallel1:
    <<: *base
  parallel2:
    <<: *base

workflows:
  version: 2
  default-test:
    jobs:
      - parallel1
      - parallel1
