on:
  push:
    paths:
      - '.ci/**'
      - '.github/workflows/**'

name: GitHub Actions
jobs:
  parallel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # no: [1]
        no: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]
    steps:
      - uses: actions/checkout@master
      - name: parallel
        env:
          DRYRUN: "true"
          TYPE: job
          PARALLEL_NO: ${{ matrix.no }}
          INTEGROMAT_WEBHOOK_URL: ${{ secrets.INTEGROMAT_WEBHOOK }}
        shell: bash
        run: ./.ci/report.sh
